### ISSUE TITLE
import plagin

### ISSUE THREAD

**Issue by gladishukD** [RonenNess/ExpiredStorage#2]
Hello! I want import this plagin but have error. How import plagin?
Help me please!!!!

**Comment by RonenNess** [comment]
I can't help you without proper error data.
Please edit your issue and include the error you're getting + addition useful data like the code that invoked the error and which browser you used.
Also please use less exclamation marks, they are unnecessary :)

Thanks.

**Comment by gladishukD** [comment]
if I use  import ls from 'expired-storage' have http://joxi.ru/RmzN11giWqGlLm or if const ls = require('expired-storage') have http://joxi.ru/p27vKKLc0MEgxm
get token
ls.getItem('token')

**Comment by RonenNess** [comment]
You need to create an instance first, it looks like you are trying to use the class type directly. Please read instructions:

https://github.com/RonenNess/ExpiredStorage/blob/master/README.md#usage

If you require it as 'ls' it supposed to be:
```javascript
var storage = new ls();
storage.getItem()
```

**Comment by gladishukD** [comment]
Thanks, I think it will help me
great plugin
